version: '3'
services:
  songs:
    build: 
      context: ../../SongDetails
      dockerfile: Dockerfile
    ports: 
      - 8088:8088
    depends_on:
      - auth
  audio:
    build: 
      context: ../../Audio
      dockerfile: Dockerfile
    ports: 
      - 8089:8089
    # environment:
    #   - DB_USER=postgres
    #   - DB_PASSWORD=admin
    #   - DB_PORT=5431
    #   - DB_NAME=musicLand
    #   - DB_HOST=localhost
    depends_on:
      - auth
  auth:
    build: 
      context: ../../Auth
      dockerfile: Dockerfile
    ports: 
      - 8087:8087
    # environment:
      # - DB_USER=postgres
      # - DB_PASSWORD=admin
      # - DB_PORT=5431
      # - DB_NAME=musicLand
      # - DB_HOST=localhost
